# Generated by Django 5.1.1 on 2024-11-02 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_alter_reaction_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('show_reactions', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='suggestion',
            old_name='suggestion_text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='suggestion',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='suggestion',
            old_name='admin',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='is_text_suggestion_enabled',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='insights.adminmessage'),
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
