# Generated by Django 5.1.1 on 2024-11-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0004_rename_show_reactions_adminmessage_is_visible_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
