# Generated by Django 5.1.1 on 2024-11-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0005_delete_suggestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminmessage',
            old_name='is_visible',
            new_name='show_reactions',
        ),
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
