# Generated by Django 5.1.1 on 2024-11-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0006_rename_is_visible_adminmessage_show_reactions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminmessage',
            old_name='show_reactions',
            new_name='is_visible',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
