# Generated by Django 5.1.1 on 2024-11-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0007_rename_show_reactions_adminmessage_is_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmessage',
            name='reaction_mode',
            field=models.CharField(choices=[('like_dislike', 'Like/Dislike'), ('text', 'Text Suggestions')], default='like_dislike', max_length=20),
        ),
    ]
