# Generated by Django 5.1.1 on 2024-11-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0008_adminmessage_reaction_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminmessage',
            name='reaction_mode',
        ),
    ]
