# Generated by Django 5.1.1 on 2024-11-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0009_remove_adminmessage_reaction_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmessage',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminmessage',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminmessage',
            name='reaction_mode',
            field=models.CharField(choices=[('like_dislike', 'Like/Dislike'), ('text', 'Text Suggestions')], default='like_dislike', max_length=20),
        ),
    ]
