# Generated by Django 5.1.1 on 2024-11-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0012_commentlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
