# Generated by Django 5.1.1 on 2024-10-31 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_alter_sale_quantity_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
