# Generated by Django 5.1.1 on 2024-10-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0003_sale_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='real_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
