# Generated by Django 5.1.1 on 2024-10-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0004_sale_real_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='quantity_sold',
            field=models.IntegerField(),
        ),
    ]
