# Generated by Django 5.1.1 on 2024-10-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0005_alter_sale_quantity_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='real_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
