# Generated by Django 5.1.1 on 2024-09-21 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_rename_c_name_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.ImageField(upload_to='')),
                ('sell_date', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=55)),
                ('payment_method', models.CharField(max_length=55)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.product')),
            ],
        ),
    ]
