# Generated by Django 5.1.1 on 2024-09-21 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_alter_sale_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='quantity',
            new_name='quantity_sold',
        ),
    ]
