# Generated by Django 5.1.1 on 2024-10-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
