# Generated by Django 5.1.1 on 2024-11-10 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0011_rename_real_price_product_bulk_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reserved_quantity',
        ),
    ]
